version: '3.5'
services:
  # fs-mongo
  fs-mongo:
    build: .
    image: amos0626/fs-mongo
    container_name: fs_mongo
    ports:
      - '8080:8080'
    volumes:
      - './logs:/root/logs'
    environment:
      - MAX_FILE_SIZE=16MB
      - MAX_REQUEST_SIZE=64MB
      - APP_LOG_LEVEL=info
      - MONGODB_URI=mongodb://base-mongo/final_fs
      # - MONGODB_URI=mongodb://amos:amos_123@base-mongo/final_fs
    depends_on:
      - base-mongo
    networks:
      - mongo-net

  # base-mongo
  base-mongo:
    image: mongo
    restart: always
    container_name: base_mongo
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: amos
    #   MONGO_INITDB_ROOT_PASSWORD: amos_123
    networks:
      - mongo-net

networks:
  mongo-net:
    name: mongo-net
    driver: bridge