version: '3.5'
services:
  fs_svc:
    build: .
    image: amos0626/fs-mongo
    container_name: fs_mongo
    ports:
      - '8080:8080'
    volumes:
      - './logs:/app/logs'
    environment:
      - MAX_FILE_SIZE=16MB
      - MAX_REQUEST_SIZE=64MB
      - APP_LOG_LEVEL=info
      # 局限性: 通过 mongo environment 配置的账号密码只能应用到 admin 数据库
      - MONGODB_URI=mongodb://amos:amos_pwd@mongo_svc/admin
    depends_on:
      - mongo_svc
    networks:
      - mongo-net

  # https://hub.docker.com/_/mongo
  mongo_svc:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: amos
      MONGO_INITDB_ROOT_PASSWORD: amos_pwd
    networks:
      - mongo-net

networks:
  mongo-net:
    name: mongo-net
    driver: bridge